export const productos = [
    {id:1, nombre:"Playstation 5", categoria:"Consolas", precio:120000, imagen:"https://www.necxus.com.ar/products_image/21441/1000x1000_2.jpg", descripcion:"Con tu consola PlayStation 5 tendrás entretenimiento asegurado todos los días. Cuenta con una interfaz de usuario más rápida y fácil de navegar que en anteriores modelos. Además, el control DualSense para PS5 combina estilo y tecnología para que jugar sea más cómodo e interactivo para todos sus jugadores. Cuenta con un procesador de 8 núcleos y uno gráfico, brinda una experiencia dinámica, respuestas ágiles, y transiciones fluidas de imágenes en alta definición."},
    {id:2, nombre:"Xbox Series X", categoria:"Consolas", precio:100000, imagen:"https://www.necxus.com.ar/products_image/22480/1000x1000_1.jpg", descripcion:"La Xbox Series X es la consola inicial de la octava generación de consolas de videojuegos, la cual fue lanzada a finales de Noviembre de 2020 y trae consigo un espectacular hardware que la convierten en la consola más potente hasta su fecha de lanzamiento."},
    {id:3, nombre:"Nintendo Switch", categoria:"Consolas", precio:80000, imagen:"https://culturageek.com.ar/wp-content/uploads/2020/08/nintendo-switch.jpg", descripcion:"Nintendo Switch es una consola desmontable, que puede usarse en modo portátil, sobremesa o en la TV; esto te brindará la posibilidad de utilizarla donde quieras y compartir sus controles. Los Joy-con cuentan con botones especiales para realizar print de pantalla. Además, posee una cámara infrarroja que puede leer la distancia respecto a los objetos e incluso detectar formas."},
    {id:4, nombre:"Elden Ring", categoria:"Videojuegos", precio:14000, imagen:"https://pbs.twimg.com/media/E3kdLoiVEAYG8qg.jpg", descripcion:"Elden Ring es el nuevo videojuego de FromSoftware, creadores de Dark Souls, Sekiro o Bloodborne. Se trata del nuevo título de acción y rol para un jugador ideado por Hidetaka Miyazaki, que en esta ocasión, estrenará un mundo abierto más grande y ambicioso. Su argumento y mitología están firmados por George R.R. Martin, autor de Canción de hielo y fuego."},
    {id:5, nombre:"Dying Light 2", categoria:"Videojuegos", precio:8000, imagen:"http://d3ugyf2ht6aenh.cloudfront.net/stores/001/783/749/products/plantilla-ps4-ps5-fisicos-psd-1-91-bf69b666e0238fa14e16295830130928-640-0.jpg", descripcion:"Dying Light 2 es la secuela del célebre título Dying Light. Apostando de nuevo por la acción y la aventura en primera persona, añadiendo parkour y saltos imposibles a su propuesta de tiroteos y combate en primera persona, Dying Light 2 nos trasladará a un mundo en el que ser el humano sobrevive como puede a la amenaza de los no muertos."},
    {id:6, nombre:"Mario Kart 8 Deluxe", categoria:"Videojuegos", precio:10000, imagen:"https://drakemall-files-new.s3.eu-central-1.amazonaws.com/Mario%20Ka-cjww7qx7y003p01zb7uvr7e0t.png", descripcion:"Mario Kart 8 Deluxe es una remasterización para Nintendo Switch de este exitoso y aclamado juego de Wii U. Además de ofrecer mejores gráficos, también contará con nuevos personajes, ajustes jugables y un renovado Modo Batalla. De esta forma, Mario Kart 8 Deluxe tendrá 48 circuitos (los 32 del original más los 16 de los DLC) y 40 personajes, cinco de ellos nuevos. Estos son Inkling chico e Inkling chica de Splatoon, el Rey Boo, Huesitos y Bowsy, así como nuevas piezas con las que configurar nuestros vehículos."},
    {id:7, nombre:"Dualsense Controller", categoria:"Accesorios", precio:20000, imagen:"https://www.fullh4rd.com.ar/img/productos/Pics_Prod/joystick-playstation-ps5-dualsense-white-0.jpg", descripcion:"El control inalámbrico DualSense para PS5 ofrece respuesta háptica inmersiva, gatillos adaptativos dinámicos y un micrófono integrado, todo en un diseño icónico. Siente la respuesta física a tus acciones en el juego con los accionadores dobles que reemplazan a los tradicionales motores de vibración. "},
    {id:8, nombre:"Xbox Controller", categoria:"Accesorios", precio:12000, imagen:"https://m.media-amazon.com/images/I/513gfnMEWnL.jpg", descripcion:"Experimenta el diseño modernizado del Control inalámbrico Xbox, con superficies esculpidas y una geometría refinada para disfrutar de una mayor comodidad durante el juego. Mantén el objetivo con el agarre texturizado y control de dirección híbrido. Captura y comparte contenido sin problemas con un botón Compartir dedicado. Empareja rápidamente, juega y cambia entre dispositivos como Xbox Series X|S, Xbox One, PC Windows 10, Android e iOS"},
    {id:9, nombre:"Joycons", categoria:"Accesorios", precio:18000, imagen:"https://planetagames.com.ar/wp-content/uploads/2018/08/Joy-Con-Green-Pink-Front-2-WEB.jpg", descripcion:"Los mandos Joy-Con son los principales controles de la consola de videojuegos Nintendo Switch. Son dos unidades individuales, cada una de las cuales contiene una palanca análoga y una matriz de botones. Pueden utilizarse mientras están conectados a la unidad principal de la consola Nintendo Switch, o separados y utilizados de forma inalámbrica; Cuando se separan, un jugador puede utilizar el par de Joy-Con o dos jugadores pueden repartírselos."}
];